name: Tag release

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check if changesets are present
        id: status
        run: npx changeset status
        continue-on-error: true # Throws when no changesets are found

      - name: Bump version and generate changelog
        if: steps.status.outcome == 'success'
        run: npx changeset version

      - name: Commit and push changes
        if: steps.status.outcome == 'success'
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore: bump version and generate changelog (bot)'

      - name: Create tag
        if: steps.status.outcome == 'success'
        run: npx changeset tag

      - name: Push tag
        if: steps.status.outcome == 'success'
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
