name: Tag release

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Changesets
        run: npm install @changesets/cli

      - name: Check if changesets are present
        run: npx changeset add --empty && npx changeset status --output changeset-status.json

      - name: Read changeset status
        id: status
        run: |
          {
            echo 'STATUS<<EOF'
            sed -e '$a\' changeset-status.json
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Check if changelog update is needed
        id: check
        run: echo "check=${{fromJson(steps.status.outputs.status).releases[0] != null}}" >> $GITHUB_OUTPUT

      - name: Bump version and generate changelog
        if: steps.status.outcome == 'success'
        run: npx changeset version

      - name: Commit and push changes
        if: steps.status.outcome == 'success'
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore: bump version and generate changelog (bot)'
